INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S1', 'SMITH', 20, 'LONDON');
INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S2', 'JONES', 10, 'PARIS');
INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S3', 'BLAKE', 30, 'PARIS');
INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S4', 'CLARK', 20, 'LONDON');
INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S5', 'ADAMS', 30, 'ATHENS');

