INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S1', 'SMITH', 20, 'LONDON');
INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S2', 'JONES', 10, 'PARIS');
INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S3', 'BLAKE', 30, 'PARIS');
INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S4', 'CLARK', 20, 'LONDON');
INSERT INTO SUPPLIER (S_ID, SNAME, STATUS, CITY) VALUES ('S5', 'ADAMS', 30, 'ATHENS');

INSERT INTO PART (P_ID, PNAME, COLOUR, WEIGHT, CITY) VALUES ('P1','NUT','RED',12,'LONDON');
INSERT INTO PART (P_ID, PNAME, COLOUR, WEIGHT, CITY) VALUES ('P2', 'BOLT', 'GREEN', 17, 'PARIS');
INSERT INTO PART (P_ID, PNAME, COLOUR, WEIGHT, CITY) VALUES ('P3', 'SCREW', 'BLUE', 17, 'ROME');
INSERT INTO PART (P_ID, PNAME, COLOUR, WEIGHT, CITY) VALUES ('P4', 'SCREW', 'RED', 14, 'LONDON');
INSERT INTO PART (P_ID, PNAME, COLOUR, WEIGHT, CITY) VALUES ('P5', 'CAM', 'BLUE', 12, 'PARIS');
INSERT INTO PART (P_ID, PNAME, COLOUR, WEIGHT, CITY) VALUES ('P6', 'COG', 'RED', 19, 'LONDON');

INSERT INTO PROJECT (J_ID, JNAME, CITY) VALUES ('J1', 'SORTER', 'PARIS');
INSERT INTO PROJECT (J_ID, JNAME, CITY) VALUES ('J2', 'DISPLAY', 'ROME');
INSERT INTO PROJECT (J_ID, JNAME, CITY) VALUES ('J3', 'OCR', 'ATHENS');
INSERT INTO PROJECT (J_ID, JNAME, CITY) VALUES ('J4', 'CONSOLE', 'ATHENS');
INSERT INTO PROJECT (J_ID, JNAME, CITY) VALUES ('J5', 'RAID', 'LONDON');
INSERT INTO PROJECT (J_ID, JNAME, CITY) VALUES ('J6', 'EDS', 'OSLO');
INSERT INTO PROJECT (J_ID, JNAME, CITY) VALUES ('J7', 'TAPE', 'LONDON');

INSERT INTO SUPPLY (S_ID, P_ID, J_ID, QUANTITY) VALUES ('S1','P1','J1',200);
INSERT INTO SUPPLY (S_ID, P_ID, J_ID, QUANTITY) VALUES ('S1', 'P1', 'J4', 700);
INSERT INTO SUPPLY (S_ID, P_ID, J_ID, QUANTITY) VALUES ('S2', 'P3', 'J1', 400);